### ISSUE TITLE
TodoListCLient SocketException in accessing to https API endpoint (hosted on Azure Web App)

### ISSUE THREAD

**Issue by kurayahi** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Specify "https://**" endpoint in "todo:TodoListBaseAddress" in App.config of TodoListCLient project.

### Any log messages given by the failure
>
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=この要求の送信中にエラーが発生しました。
  Source=mscorlib
  スタック トレース:
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   場所 TodoListClient.MainWindow.<AddTodoItem>d__14.MoveNext() (C:\tmp\active-directory-dotnet-native-aspnetcore-v2-master\TodoListClient\MainWindow.xaml.cs):行 209

内部例外 1:
WebException: 接続が切断されました: 送信時に、予期しないエラーが発生しました。。

内部例外 2:
IOException: 転送接続からデータを読み取れません: 既存の接続はリモート ホストに強制的に切断されました。。

内部例外 3:
SocketException: 既存の接続はリモート ホストに強制的に切断されました。

### Expected/desired behavior
>
No exception.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 

### Mention any other details that might be useful
In my environment, API service is hosted by Azure Web App.
This is issue regarding "todo:TodoListBaseAddress" in App.config of TodoListCLient project, when I specify "http://**" endpoint, it does work, however when I change it to "https://***" endpoint it fails with following error.

It seems that this error is caused by HTTP client library. Because, my other REST client can access to the same "https://***" endpoint successfully.

The exception point is as below.
[MainWindow.xaml.cs]
HttpResponseMessage response = await httpClient.PostAsync(todoListBaseAddress + "/api/todolist", content);
[Exception]
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.

I'm now looking up how to fix this issue.

**Comment by jmprieur** [comment]
@kurayahi 
apparently there were changes in Azure web apps that require TLS 1.2

Do you want to try to add the following line, for instance at the beginning of Main in Program.cs?

```CSharp
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
```

**Comment by kurayahi** [comment]
Thanks , I got it. It works well.
I added the line in MainWindow.xaml.cs of TodoListClient project.
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

**Comment by jmprieur** [comment]
@kurayahi 
Actually, after discussing with colleagues, this does not seem to be the thing to do. 
The issue you see seems to come from the OS.

The following article will help you doing the right fix (which is not in the code of the app): [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)

Fixed by moving the client to .NET Framework 4.7.1 as advised: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/commit/b04701638d089f5bba346f107b829aa594cb2e79
