### ISSUE TITLE
The calling thread cannot access this object because a different thread owns it

### ISSUE THREAD

**Issue by ivikashjha** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#103]
AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope

**Comment by jmprieur** [comment]
@ivikashjha : do you have repros steps?
Can you please share a call stack?

**Comment by ivikashjha** [comment]
[External Code]
TodoListClient.exe!TodoListClient.MainWindow.AddTodoItem(object sender, System.Windows.RoutedEventArgs e) Line 195
	at C:\AzureAd\active-directory-dotnet-native-aspnetcore-v2\1. Desktop app calls Web API\TodoListClient\MainWindow.xaml.cs(195)
[Resuming Async Method]
[External Code]

**Comment by jmprieur** [comment]
Thanks @ivikashjha 
I think I know what happens. We need to fix it

**Comment by jmprieur** [comment]
This should be fixed bu this PR (which is to move to .NET Core 3.0, but also fixes a number of issues)
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/pull/111
