### ISSUE TITLE
GetAccessTokenOnBehalfOfUserAsync: lazy ObO does not respect tenant parameter

### ISSUE THREAD

**Issue by zvrba** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#106]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Scenario: a user from tenant A (call it u@A) logs in as a guest into tenant B (call it u@B). As u@B it uses a native client to acquire a token for a web api, and the token is correct (`iss` is B, `idp` is A). The web api uses ObO to acquire a MS Graph token. `GetAccessTokenOnBehalfOfUserAsync` as it is, returns a token for u@A (with `iss` being A). When this token is subsequently used against an object (say, a group) in B, the Graph API returns not found as it searches in the tenant A instead of B.

### Expected/desired behavior
`tenant` parameter of `public async Task<string> GetAccessTokenOnBehalfOfUserAsync(IEnumerable<string> scopes, string tenant = null)` should also be respected for "lazy ObO". (File is `TokenAcquisition.cs`).

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
Latest as of writing, https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/commit/04c11119df5ec2f2d38e3ed4b9969a6a3e37800e

### Details
The following patch solves the problem for me. I don't know how to "properly" integrate it with the rest of the code (e.g., hard-coded authority) if this is necessary.

```
Index: Microsoft.Identity.Web/TokenAcquisition.cs
===================================================================
--- Microsoft.Identity.Web/TokenAcquisition.cs	(revision 3734)
+++ Microsoft.Identity.Web/TokenAcquisition.cs	(working copy)
@@ -170,10 +170,12 @@
             if (jwtClaim != null)
             {
                 (CurrentHttpContext.User.Identity as ClaimsIdentity).RemoveClaim(jwtClaim);
-                var result = await application
-                    .AcquireTokenOnBehalfOf(scopes.Except(_scopesRequestedByMsalNet), new UserAssertion(jwtClaim.Value))
-                    .ExecuteAsync()
-                    .ConfigureAwait(false);
+                var builder = application
+                    .AcquireTokenOnBehalfOf(scopes.Except(_scopesRequestedByMsalNet), new UserAssertion(jwtClaim.Value));
+                if (tenant != null)
+                    builder = builder.WithAuthority($"https://login.microsoftonline.com/{tenant}/v2.0/");
+
+                var result = await builder.ExecuteAsync().ConfigureAwait(false);
                 return result.AccessToken;
             }
             else
```

**Comment by jmprieur** [comment]
Thanks @zvrba for the update
