### ISSUE TITLE
The native app calls web api needs the step by step WPF instructions

### ISSUE THREAD

**Issue by mahoekst** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#108]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#How-was-the-code-created

Doesn't have the instructions for the WPF client

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
Fixed by commit https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/commit/a1be244790f3cb71bf9590ad7ba105416636a803
