### ISSUE TITLE
An error occurred while calling the downstream API

### ISSUE THREAD

**Issue by zmsoft** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#109]
### This issue is for a: (mark with an `x`)
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
>Follow the official documentation guide

### Any log messages given by the failure
>Bad Request
An error occurred while calling the downstream API
Authority should be in the form <host>/<audience>,for example 
https://login.microsoftonline.com/common
![image](https://user-images.githubusercontent.com/8024438/67258168-f0f58b00-f4c1-11e9-9f9a-fc0c71fb6f42.png)

### OS and Version?
> Windows  10

### Versions
>Latest as of writing

**Comment by jmprieur** [comment]
Cmlosing as there is no more information.
This should work. See https://github.com/AzureAD/microsoft-identity-web
