### ISSUE TITLE
AppCreationScripts for folder 3 creates two apps.

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Go to "3.-Web-api-call-Microsoft-graph-for-personal-accounts"
> Run the app creation scripts

### Expected/desired behavior
> In this folder, only one app should be created
> however 2 apps are currently created

**Comment by TiagoBrenck** [comment]
Fixed
