### ISSUE TITLE
Two different Microsoft.Identity.Web repositories

### ISSUE THREAD

**Issue by tbebekis-ax** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#119]
Hi all and many thanks for your samples.
 
There are two, at least, repositories containing the Microsoft.Identity.Web

- 	https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2
- 	https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2

and as far as I can tell there must be differences between the two.

1. Why is that?
2. What should I use?

Regards
Theo

**Comment by TiagoBrenck** [comment]
We are trying to merge them in the future, but there are some pending discussions that need to be solved before we merge them. So far, the core idea of the library is the same in both samples, however, active-directory-dotnet-native-aspnetcore-v2 has some features that only applies on Web APIs, while active-directory-aspnetcore-webapp-openidconnect-v2 is more focused on Web Apps.

@jmprieur I remember you mentioning that you have a branch where you syncing the Identity library. Have you merged it already?

**Comment by tbebekis-ax** [comment]
I have an Azure AD protected ASP.Net Core WebApi. 

In the same solution I have two clients to that WebApi: a WinForms application (Client credentials flow) and an ASP.Net Core Mvc Web App (Implicit grant flow). 

So I wanted a single code base of that Microsoft.Identity.Web project.

Anyway, I've done it now and they all work fine.

But it would be nice to have it all in one.

Thanks
Theo.
