### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by MullerWasHere** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#12]
Hi all.

I Followed every step and on the WPF application i get the error "You do not have permission to view this directory or page."

Any clues?

Thank you

**Comment by Katydude** [comment]
Take a look at the issue I closed today regarding the 500 errors and see if it offers you any insight. If not, I'll try to help.

**Comment by jmprieur** [comment]
@MullerWasHere can you provide repro steps? a call stack? where do you see the error?

**Comment by jmprieur** [comment]
@MullerWasHere : closing this issue as you have not provided more information. 
Feel free to re-open if you still hit this
