### ISSUE TITLE
Provide a variation with manual Jwt validation

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#122]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Have an additional folder with a v2.0 sample showing how to manually validate the token like in this v1.0 sample: https://github.com/azure-samples/active-directory-dotnet-webapi-manual-jwt-validation

cc: @TiagoBrenck @kalyankrishna1

**Comment by TiagoBrenck** [comment]
@jmprieur the manual validation done in this v1 sample, is happening in Microsoft.Identity.Web (validate audience, issuer with different aliases, if access token has scope/roles). Are you suggesting a sample that doesn't use Identity.Web, but does all the validations in Startup.cs?

**Comment by jmprieur** [comment]
@TiagoBrenck, I thought that the manual validation was more about using the `SecurityToken` classe. 
https://github.com/Azure-Samples/active-directory-dotnet-webapi-manual-jwt-validation/blob/96fb3b6076f8927753f75e2b8eab52510111f729/TodoListService-ManualJwt/Global.asax.cs#L146-L147

**Comment by TiagoBrenck** [comment]
If you think that this is not a duplication of work, then lets keep this task.

**Comment by jmprieur** [comment]
See https://github.com/Azure-Samples/active-directory-dotnet-webapi-manual-jwt-validation
