### ISSUE TITLE
Microsoft.Identity.Web should not directly reference JwtSecurityToken or JwtSecurityTokenHandlers

### ISSUE THREAD

**Issue by brentschmaltz** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#129]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Some of the instances are public.
There may be others.
Review:
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/8abfdfceab88bc79003a84b093d1b606cbda49e7/Microsoft.Identity.Web/HttpContextExtensions.cs#L14

https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/8abfdfceab88bc79003a84b093d1b606cbda49e7/Microsoft.Identity.Web/HttpContextExtensions.cs#L24

https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/8abfdfceab88bc79003a84b093d1b606cbda49e7/Microsoft.Identity.Web/TokenAcquisition.cs#L184

https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/8abfdfceab88bc79003a84b093d1b606cbda49e7/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs#L66

https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/8abfdfceab88bc79003a84b093d1b606cbda49e7/Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs#L118
### Any log messages given by the failure
>

### Expected/desired behavior
> It would be best if Microsoft.Identity.Web did not directly reference System.IdentityModel.Tokens.Jwt as this pulls in newtonsoft libraries.
We want to remove this dependency as Microsoft does not own these libraries and there are breaking changes across versions.

In addition, if the asp.net runtime returns other than a JwtSecurityToken, these methods will be broken.

If additional API's are needed to normalize accessing properties in a SecurityToken we should add those.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@brentschmaltz do we want to use JsonWebToken instead?

**Comment by brentschmaltz** [comment]
@jmprieur your api's should use SecurityToken.
You will then need to cast to either JwtSecurityToken or JsonWebToken until we get the apis we need on SecurityToken.

**Comment by jmprieur** [comment]
so what is the suggestion?

**Comment by brentschmaltz** [comment]
@jmprieur 

Any public apis's take a Microsoft.IdentityModel.Tokens.SecurityToken.
Then internally cast to JwtSecurityToken or JsonWebToken to get values from the token.
This will work for any tokens from IdentityModel.

You would need extensibility something like the extensibility in TokenValidationParameters seen used here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/34a097ed2a97f1c8d06722bc6d6dca0594f0ed62/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs#L1219

However, since Microsoft.Identity.Web is a helper to asp.net adn asp.net will only surface JwtSecurityToken NOW and perhaps JsonWebToken in the future, casting should be enough for now.

**Comment by jmprieur** [comment]
This is now handled in Microsoft.Identity.Web
Will change the implementation when ASP.NET Core does.
