### ISSUE TITLE
Internal 500 Error

### ISSUE THREAD

**Issue by Katydude** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Open App.config in TodoListClient. Does the {0} area need completing? If not, and it is a static string, why is it in App.config? It is confusing.

### Any log messages given by the failure
> 500 Internal Error is returned by the application when run after following the tutorial's instructions. Is it because of a missing step, maybe involving this App.config parameter?

### Expected/desired behavior
> After authenticating and approving the client application's permissions, the Todo list service should return results, not a 500 Internal Server Error.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) Windows 8.1

### Versions
>

### Mention any other details that might be useful
All instructions in the tutorial were followed. The TLS1.2 protocol was explicitly specified before calling in case that had something to do with it. The applications (service and client) are running locally on the ports specified in the downloaded code. My credentials appear to be accepted. I am asked to grant the application local permissions and I did so.

Lastly, instructions for rejecting / resetting the application's security policy so the whole process could be run through again would be helpful.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Katydude** [comment]
Never mind about the App.config parameter. After looking over it again I do see where this is an optional, although mis-formatted / incorrect use of a configuration parameter as the parameter use is sort of overloaded. I still get the 500 Internal Server Error returned from the service, though, so I am going to leave this ticket open.

**Comment by Katydude** [comment]
More information: The Authority in the ConfigureAzureOptions class ends up with a double // in the middle of it: https://login/microsoftonline.com//v2.0/

This can't be right, can it?

Also, the same set of options shows that the Client Secret is empty. Don't all client applications need to pass in a client secret for authentication?

Just trying to track down the source of my 500 errors since this type of error is so difficult to get diagnosed by MSFT support.

**Comment by Katydude** [comment]
So...there are two HUGE issues with this tutorial. First, it doesn't mention (at least I don't see where) that you MUST trust your Localhost certificate into your localmachine trusted roots. Otherwise, the client application is not going to connect to the service app. (As for what this means when you try to deploy to Azure....I suspect you will also need to take care that https is correctly configured there, as well. 500 errors are NOT any help with diagnosing this problem.)

And, secondly...and this is the BIG problem with this code: It absolutely will NOT work if you omit the Domain and TenantID parameters in appsettings.json. I don't care what the comments in the file say, I wasted 4 hours as well as signed up for two different Azure Pay As You Go accounts to try to troubleshoot why the application would not run. So...I really hope all of my pain helps someone else out.

And this needs to be addressed in the downloaded code as well as the tutorials.

**Comment by jmprieur** [comment]
Thanks for your feedback and really sorry for your pain @Katydude.

To answer your question, ida:AADInstance in the App.Config can be used in the case of national or sovereign clouds (I've added a comment and a link for more details)

Indeed, as you have discovered, https://login/microsoftonline.com//v2.0/ was not right. the ida:TenantId property is needed.

As far as trusting your localhost certificate is concerned, can you please tell me more how you ran the Web API locally? did you use IIS express (which does setup the cert correctly?) or did you do something else?

**Comment by jmprieur** [comment]
@Katydude also which browser was your default browser in Visual Studio? how did you accept the localhost certificate into your local machine trusted roots (did you use the cert manager)? Can you please share more about the specifics? I was not able to repro your issues myself;

**Comment by Katydude** [comment]
Yes, I was using IIS Express which makes its own certificate but does not add it as a trusted root.

I accepted the certificate into my store using PowerShell but you could also just browse to an IIS Express website, grab the certificate by examining it with IE or Chrome, exporting it to the desktop and then importing it into your trusted roots of LocalMachine. You could also just change your IIS Express certificate to use your own. All of this is easy to figure out via DuckDuckGo (!) once you know you need to do it.

My default browser was IE 11 on Windows 8.1 and Visual Studio 2017 Community 15.8.9. The rest of the settings (.NET 4.6.1, etc.) were all inherited from the sample code I downloaded here.

**Comment by Katydude** [comment]
JM,

I know this is slightly off-topic but have you had any success authenticating to an existing App Service to make REST calls? I think that would make a great addendum to your docs if not a whole new project altogether if there are significant differences. I could not figure out how to expose an API / Scope on an existing App Service. I have several of them at the moment so if I could just use what I've already deployed without making a new Web App that would be awesome.

**Comment by jmprieur** [comment]
@Katydude : by App Service, do you mean a Web API? (ASP.NET / ASP.NET Core Web API hosted in [Azure](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet)) or something else?

If those are existent Web APIs, I guess they accept v1 tokens (whereas the sample here is a v2.0 sample on the new clean stack, which accepts v2.0 tokens). In that case the scope you need to use is described in [Scopes for a v1.0 application](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#scopes-for-a-v10-application)
