### ISSUE TITLE
How to limit users to my organization?

### ISSUE THREAD

**Issue by sam-wheat** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#147]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Set configuration values per instructions

### Any log messages given by the failure
> Visual Studio crashes 

### Expected/desired behavior
> Only users in my domain are authenticated  

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

Per the instructions:

[Optional] if you want to limit sign-in to users in your organization, also update the following properties:
Domain, replacing the existing value with your AAD tenant domain, for example, contoso.onmicrosoft.com.
TenantId, replacing the existing value with the Tenant ID.

I tried all combinations of using tenant id (GUID) and domain (me.onmicrosoft.com) and none of them work.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@sam-wheat : did you read this part of the README.md ? https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#important-note ?

**Comment by sam-wheat** [comment]
Hi Jean-Marc, thanks for your reply.
I understand the documentation to indicate the following should work:

 /*
      You need specify the TenantId only if you want to accept access tokens from a single tenant (line of business app)
      Otherwise you can leave them set to common
    */
    "Domain": "mydomain.onmicrosoft.com", // for instance contoso.onmicrosoft.com. Not used in the ASP.NET core template
    "TenantId": "99997985-90e5-479d-9edf-9ef5ce5b4123" // The tenant's Directory ID (a guid) or 'common' or 'organizations' or 'consumers'

The guid I am using is from the Directory + subscription filter.  Top menu bar, icon is a book + funnel.   Is this correct?

Thanks

**Comment by jmprieur** [comment]
Yes @sam-wheat, this is correct. You can also find it in the Properties for a given active directory (Directory ID).
Alternatively you can use the domain name as the tenant ID. This also works.

**Comment by sam-wheat** [comment]
It does not work.  Am I missing some other configuration item?

            HttpResponseMessage response = await _httpClient.PostAsync(TodoListApiAddress, content);

            if (response.IsSuccessStatusCode)
            {
                TodoText.Text = "";
                GetTodoList();
            }
            else
            {
                    await DisplayErrorMessage(response);
            }

Result is 401 error.

> {StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Date: Fri, 26 Jun 2020 14:05:17 GMT
  Server: Microsoft-IIS/10.0
  WWW-Authenticate: Bearer error="invalid_token", error_description="The signature key was not found"
  X-Powered-By: ASP.NET
}}

**Comment by jmprieur** [comment]
Which token did you provider? Would it be an Azure AD token for B2C or the contrary?
Did you try using the app creation scripts @sam-wheat ?

**Comment by sam-wheat** [comment]
> Which token did you provider? Would it be an Azure AD token for B2C or the contrary?
Sorry I don't understand this.

> Did you try using the app creation scripts @sam-wheat ?
I did not use the scripts since this is a learning experience for me.  Everything else seems to be working however.

**Comment by speschka** [comment]
FWIW...I got the "signature key was not found" error once when I tried a todo:TodoListScope value (in the app.config file) that was not part of the scopes defined for the app.  Sharing just in case.
