### ISSUE TITLE
JWT authorization fail

### ISSUE THREAD

**Issue by wilsonlintm** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#167]
Hi, 
I have download webapi sample from below, and I have followed the instruction.
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/archive/aspnetcore3-1.zip

Then, I have acqired the token in angular from msal
// Silently request an access token
    async getAccessToken(): Promise<string> {
        let result = await this.msalService.acquireTokenSilent(OAuthSettings)
            .catch((reason) => {
                //       this.alertsService.add('Get token failed', JSON.stringify(reason, null, 2));
            });

        if (result) {
            return result.accessToken;
        }
        return null;
    }

Then I pass this accessToken to webcore api as above, it throws 401 error.

So, there will possible two direction causing the problem, 
1. azure setting? (supposingly followed the instruction)
2. Startup.cs for jwt

I guess the #2 is the highest chance causing the problem . Did anyone know how to fix this?

Cheers,
Wilson

**Comment by Shama-K** [comment]
Can you provide below details:

- What is the value of scope for resource in OAuthSettings?
- Is **aud** claim in the Access Token is client id of your Web API? If yes, then what is the format?

**Comment by jennyf19** [comment]
closing, as more info needed. Feel free to reopen @wilsonlintm
