### ISSUE TITLE
ADB2C Bearer error="invalid_token", error_description="The audience '' is invalid" 

### ISSUE THREAD

**Issue by sethuraj** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#170]
I tried your application against my ADB2C tenant.  Everything from the sample was added to my API, except,In the appsettings  I  added SignUpSignInPolicyId with my user flow.
I created valid ID token and used swagger (postman) to run my api and I am getting this error message.

Bearer error="invalid_token", error_description="The audience '<webapp registeredclientID>' is invalid" .

**Comment by jmprieur** [comment]
You also need to do your own app registration and update the client ID, domain, etc ... in the appsettings.json, @sethuraj

**Comment by xz013** [comment]
> You also need to do your own app registration and update the client ID, domain, etc ... in the appsettings.json, @sethuraj

please do you have any example how to do that  ! 
and thank you for helping

**Comment by jmprieur** [comment]
@xz013 : See https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga

**Comment by jennyf19** [comment]
closing as answered...feel free to reopen @sethuraj

**Comment by sethuraj** [comment]
Thanks, I will check this out. This was for api to validate the token at starttup. UI side was straight forward.  
I am now able to validate the token on api side, with a Middleware class implementation and Startup code.
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(jwtOptions =>
            {......}

**Comment by jennyf19** [comment]
thanks for the quick response @sethuraj 
you might be interested in [Microsoft Identity Web](https://github.com/azuread/microsoft-identity-web), the wiki there has more information and code snippets

**Comment by bz-wow** [comment]
> thanks for the quick response @sethuraj you might be interested in [Microsoft Identity Web](https://github.com/azuread/microsoft-identity-web), the wiki there has more information and code snippets

Not an issue, just a complaint... Why MS provides so many packages to just acquire a token? It's very hard to just pick one of them, since lost of articles saying how to get/set an AAD token, and these methods are not consistent... Didn't find a simple and clear enough guide so far...

**Comment by jennyf19** [comment]
@bz-wow Thanks for the feedback. What specifically are you looking for as far as documentation? And if you can provide links to the docs you've seen that are not helpful or clear, that would enable us to make improvements there as well. thanks.

Have you seen this page on [token cache serialization](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore)?
