### ISSUE TITLE
Document for sample "3.-Web-api-call-Microsoft-graph-for-personal-accounts" missed to mention to setup Web redirect URL.

### ISSUE THREAD

**Issue by dylanwa** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#174]
### This issue is for sample '3.-Web-api-call-Microsoft-graph-for-personal-accounts'

Need to have the step to add Web redirect URL, like "https://localhost:44351/", but the document duplicated the step of add "API Permission" for client and service App.

**Comment by Shama-K** [comment]
Why do you need Web redirect URL, like "https://localhost:44351/"? Document represents a scenario where WPF Desktop application calls an ASP.NET Core Web API. For that required Redirect URI is:  https://login.microsoftonline.com/common/oauth2/nativeclient.
Other issue of duplicate step of add "API Permission" will be handled.

**Comment by dylanwa** [comment]
@Shama-K , I tried it, without this local web api as redirect url, the sample does not work. The sample is a WPF client call todo WebAPI, then todo WebAPI call graph API.

**Comment by jmprieur** [comment]
@dylanwa : the redirect URI on the Web API is for the multi-tenant case (Sing-in Audience = organizations or organizations and personal accounts). In that case the user or tenant admin is invited to consent to the web API to be installed in the tenant (and for this there is an authorization happening. Then the user is redirected to this page: [index.html](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/wwwroot/index.html)

**Comment by jmprieur** [comment]
Closing as I believe this was addressed. @dylanwa feel free to reopen if you disagree
