### ISSUE TITLE
Need Admin Approval (Desktop App Calls Web Api)

### ISSUE THREAD

**Issue by BrettBailey** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#176]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Follow instructions in step 1 Desktop App Calls Web Api

### Any log messages given by the failure
>aad-todolist-client needs permission to access resources in your organisation that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

### Expected/desired behavior
> User Approval required, not admin.  

### OS and Version?
> Windows 10

### Versions
> Fresh version cloned from master today 03 Nov 2020

### Mention any other details that might be useful
I've checked the app registrations and neither show admin consent required
double checking the app registration for the service and the scope I added under "expose an API" is showing as "Admins and users" and state is enabled.

> ---------------------------------------------------------------
![image](https://user-images.githubusercontent.com/2833704/98003191-5a52ee00-1de6-11eb-8598-2a8b0ebd7200.png)
![image](https://user-images.githubusercontent.com/2833704/98003286-7a82ad00-1de6-11eb-9da0-46162e4dc8aa.png)
![image](https://user-images.githubusercontent.com/2833704/98003379-98501200-1de6-11eb-8b96-8e38cd83d380.png)

> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@BrettBailey it can be that your tenant id demands that users cannot consent. 
This is therefore not an issue with the sample, but a tenant setting;

**Comment by BrettBailey** [comment]
@jmprieur Thanks for getting back to me.   I didn't know about that feature but I've had a look in AD and found the setting under "Enterprise Applications". You are correct it was set to not allow user consent.
