### ISSUE TITLE
About from "AddAzureADBearer" to "AddMicrosoftIdentityWebApiAuthentication"

### ISSUE THREAD

**Issue by zorc** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#183]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Our projects need get configs from Azure web app environment variable like this:

`services.AddAuthentication(AzureADDefaults.JwtBearerAuthenticationScheme)
.AddAzureADBearer(options =>{
options.Instance = Environment.GetEnvironmentVariable("AzureAd-Instance");
options.TenantId = Environment.GetEnvironmentVariable("AzureAd-TenantId");
options.ClientId = Environment.GetEnvironmentVariable("AzureAd-ClientId");
options.Domain = Environment.GetEnvironmentVariable("AzureAd-Domain");
});`

But I don't know how to do it in the “AddMicrosoftIdentityWebApiAuthentication”，it only read configs from appsettings.json.

### Expected/desired behavior
>Keep “AddAzureADBearer” or support read configs from other way in "AddMicrosoftIdentityWebApiAuthentication"

### OS and Version?
> Windows 10

### Versions
>1.4.1

### Mention any other details that might be useful
> Thanks a lot!

**Comment by jmprieur** [comment]
@zorc 
you can use:

```CSharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
           .AddMicrosoftIdentityWebApi(options => {});
   ...
```

`AddMicrosoftIdentityWebApi` has an override with delegates to initialize the options as you want.

**Comment by jrmcdona** [comment]
@jmprieur does this work with this too? 

 services.AddMicrosoftIdentityWebApiAuthentication(Configuration);

**Comment by jmprieur** [comment]
@jrmcdona, in that case, I'd recommend you use:

```CSharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
           .AddMicrosoftIdentityWebApi(options => {});
```

The 2 instructions form gives you more flexibility (`AddMicrosoftIdentityWebApiAuthentication` is really a shortcut for the 2 instructions, for simple cases. In advanced cases, rather use the 2 instructions)

You can also override the JwtBearerOptions if you need. See https://github.com/AzureAD/microsoft-identity-web/wiki/customization#customization-in-the-startupcs

To find answers to your last 2 questions, I'd recommend you look at the Microsoft.Identity.Web wiki: https://github.com/AzureAD/microsoft-identity-web/wiki

**Comment by jennyf19** [comment]
closing as answered
