### ISSUE TITLE
Can't change "Who Can Consent" to "Admins and Users" when adding Scope to Expose an API

### ISSUE THREAD

**Issue by dbman86** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#186]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I am trying to follow the tutorial for chapter 1.  When I go to expose an API and add a scope, I don't see the option to change the "Who Can Consent" to admins and users:
![image](https://user-images.githubusercontent.com/629163/108633162-9d81ad00-7427-11eb-934c-90b84b589923.png)

Users are allowed to consent to any app in the Enterprise Applications -> Consent and Permissions settings...

![image](https://user-images.githubusercontent.com/629163/108633082-2fd58100-7427-11eb-969c-74dd47d287a1.png)

Does anyone know why I can't change this??

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> that the tutorial would be clear why I would be unable to change "Who Can Consent" to admins and users, and how to fix this.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
N/A

### Versions
> N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Shama-K** [comment]
It looks like you are using Azure AD B2C tenant and Azure AD B2C does not support user consent.

**Comment by dbman86** [comment]
thanks this is actually a better tutorial for what I am trying to accomplish: https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/
