### ISSUE TITLE
Cleanup.ps1 fails with exception

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#191]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run cleanup.ps1 and log in with a tenant admin account

Remove-AzureADApplication : Error occurred while executing RemoveApplication
Code: Request_BadRequest
Message: Value cannot be null.
Parameter name: requestContext
RequestId: e3a649e4-ec3a-4538-91af-c2143003fc84
DateTimeStamp: Mon, 22 Mar 2021 09:40:28 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At C:\g\samples\active-directory-dotnet-native-aspnetcore-v2\1. Desktop app calls Web
API\AppCreationScripts\Cleanup.ps1:63 char:137
| ForEach-Object {Remove-AzureADApplication -ObjectId $_.ObjectId }

    + CategoryInfo          : NotSpecified: (:) [Remove-AzureADApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.RemoveA
   pplication

**Comment by Shama-K** [comment]
@bgavrilMS Can you please share what is the "signInAudience" in the App manifest?  
Remove-AzureADApplication does not work if app is registered for **AzureADandPersonalMicrosoftAccount**. That needs to be removed manually.

**Comment by bgavrilMS** [comment]
Well the ./Create.ps1 script says to update the SIgnInAudience to `AzureADandPersonalMicrosoftAccount`, so I did that. The Cleanup.ps1 script should catch this exception and ask the user to manually remove apps if the underlying operation is not automatable.
