### ISSUE TITLE
Possible typo/out of date code in the tutorial

### ISSUE THREAD

**Issue by reagcz** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#197]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
[This part of the tutorial](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/3.-Web-api-call-Microsoft-graph-for-personal-accounts) calls for replacing

```CSharp
services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
    .AddInMemoryTokenCaches();
```
[Here](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph/TodoListService/Startup.cs)
with

```CSharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddMicrosoftWebApi(options =>
    {
        Configuration.Bind("AzureAd", options);
        options.Events = new JwtBearerEvents();
        options.Events.OnTokenValidated = async context =>
        {
            // This check is required to ensure that the Web API only accepts token from it's own client.
            if (context.Principal.Claims.Any(x => (x.Type == "azp" || x.Type == "appid") && x.Value != Configuration["AzureAd:ClientId"]))
            {
                throw new UnauthorizedAccessException("Client is not authorized to access the resource.");
            }
            else
            {
                throw new UnauthorizedAccessException("Application ID claim does not exist for the client.");
            }
        };
    }, 
    options =>
    {
        Configuration.Bind("AzureAd", options);
    })
        .AddMicrosoftWebApiCallsWebApi(Configuration)
        .AddInMemoryTokenCaches();`
```

**I found two issues with this**
1.  calling `.AddMicrosoftWebApi` results in an unknown reference, despite using the same versions of NuGet packages as the demo. This seems to be resolved by replacing it with `.AddMicrosoftIdentityWebApi`
2.  The main issue is that the method `.AddMicrosoftWebApiCallsWebApi(Configuration)` doesn't seem to exist, nor did I find any other reference.
### Any log messages given by the failure
>
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MicrosoftIdentityWebApiAuthenticationBuilder' does not contain a definition for 'AddMicrosoftWebApiCallsWebApi' and no accessible extension method 'AddMicrosoftWebApiCallsWebApi' accepting a first argument of type 'MicrosoftIdentityWebApiAuthenticationBuilder' could be found (are you missing a using directive or an assembly reference?)
`

### Versions
>
- Microsoft.Identity.Web 1.9.1
- Microsoft.Identity.Web.MicrosoftGraph 1.9.1
- Microsoft.AspNetCore.Authentication.JwtBearer 3.1.10
- Runtime is .net core 3.1

**Comment by jmprieur** [comment]
@Shama-K @kalyankrishna1 can you please take this one?
It's indeed referencing an old version of Ms.Id.Web
but I also I don't understand why we have a special token validation? shouln't it be in Microsoft.Identity.Web if it needs to happen?

**Comment by jennyf19** [comment]
fixed, thank you @reagcz
