### ISSUE TITLE
AppCreationScripts - can no longer change audience to AzureADandPersonalMicrosoftAccount

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#207]
This issue is a regression.

1. Run the AppCreationScripts for chapter 2 (or any of them)
2. The instructions say to manually change the SignInAudience to AzureADandPersonalMicrosoftAccount (for both client and server app)
3. Try to do that by editing the manifest

**Actual**: Failed to update TodoListClient(ms-identity-dotnet-native-aspnetcore-v2) application. Error detail: Property accessTokenAcceptedVersion is invalid. [Iz/52T1c15CuKbC7aTnO6Q]

**Comment by jmprieur** [comment]
This seems to be an error with the portal / app-model
There shouldn't be an accessTokenAcceptedVersion for the client, as it's not a web API?
Which folder is this @bgavrilMS ?
