### ISSUE TITLE
401 Unauthorized returned from App Service after publishing to Azure

### ISSUE THREAD

**Issue by tbaggs** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#25]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tbaggs** [comment]
This issue is for a: (mark with an x)

- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

Minimal steps to reproduce
1. Publish API to Azure App Service following instructions in documentation
2. Using the UWP client, attempt to access the API after authenticating
3. Azure App Service returns 401 Unauthorized without ever hitting the API controller
4. I added NSwag to my API and was able to auth through my browser and hit the controller using the /Swagger route

Any log messages given by the failure
I am just seeing 401s in the App Insights log

Expected/desired behavior
UWP app would auth and get a response from the API

OS and Version?
Window 10 with Visual Studio 2017

Versions

Mention any other details that might be useful

**Comment by tbaggs** [comment]
After turning on Diagnostic logging in the App services I did get the following error page which is showing the error occurring in the EasyAuth module of the App Service.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 401.83 - Unauthorized</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 401.83 - Unauthorized</h3> 
<h4>You do not have permission to view this directory or page.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul>       <li>The authenticated user does not have access to a resource needed to process the request.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul>       <li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;EasyAuthModule_32bit</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;AuthenticateRequest</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80004005</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://{removed intentionally}-dev-webapi:80/api/Notifications</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\api\Notifications</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This is the generic Access Denied error returned by IIS. Typically, there is a substatus code associated with this error that describes why the server denied the request. Check the IIS Log file to determine whether a substatus code is associated with this failure. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=401,83,0x80004005,14393">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
  
 
</fieldset> 
</div> 
</div> 
</body> 
</html>

**Comment by RenePingen** [comment]
We are getting the same issue when using an app service as web api. We have both tried with the managed identity on the app service and through the powershell script to create the apps. Both cases result in the situation that manual authentication on the API works, but through the native client we get the following error (401.83):
{"code":401,"message":"IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier\u000d\u000a    (\u000d\u000a    IsReadOnly = False,\u000d\u000a    Count = 1,\u000d\u000a    Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause\u000d\u000a

**Comment by jmprieur** [comment]
@RenePingen 
I suspect a TLS 1.2 issue
could you please change the Target Framework in the properties of the TodoList client to .NET Framework 4.7.2?

![image](https://user-images.githubusercontent.com/13203188/55874936-13fac600-5b94-11e9-9aea-7bb66740797f.png)

If this works, I'll create a PR to update the client

**Comment by RenePingen** [comment]
@jmprieur Thanks for the quick response. I changed it to 4.7.2 but unfortunately im still receiving the same error.

**Comment by jmprieur** [comment]
@brentschmaltz @mafurman @GeoK do you have an idea? this seems to be related to Wilson?

**Comment by GeoK** [comment]
@jmprieur - The log message is coming from Wilson, `IDX10500: Signature validation failed`, but it looks like the version used is 4x.
This class doesn't exist in 5x: `System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause`

**Comment by brentschmaltz** [comment]
@RenePingen George is correct here. This seems an odd issue because asp.net core uses IdentityModel 5.4 and this class is in 4.x. What IdentityModel assemblies does your application reference?

**Comment by RenePingen** [comment]
I am trying to use the built in azure ad authentication. Am I  running into the limitation mentioned here?
https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization

I also tried with the older example of the native client, but i got the same error.

Either way, im trying to get the combination native client and nodejs API combination to work. Any ideas are welcome :)

**Comment by brentschmaltz** [comment]
@jmprieur do you have a contact for Azure Functions?

**Comment by RenePingen** [comment]
Hi all,

Thanks for the help. Turns out the only option was to use the ADAL authentication for now, using the older sample: 
https://azure.microsoft.com/nl-nl/resources/samples/active-directory-dotnet-native-aspnetcore/

For now it seems this is the only way to use the built in app service authentication.

Steps i followed:
1. Create AAD apps as described in the provided example. Explicitly set 	"accessTokenAcceptedVersion": 1 for the client app.
2. Use the built in authentication module in the Azure App service
3. update the details as provided in the todolist client (i didnt run the full todolist example, but merely tested authentication).
4. Test by running the Todolistclient, obtain the token and use the token to call your app service.

This issue can be closed.

Thanks!

**Comment by jmprieur** [comment]
thanks for the update @RenePingen 
I'll keep it open, as I want to find a solution (eventually, probably after Build 2019)

**Comment by AhmedAzzabi** [comment]
Any updates on this, i'm still facing same issue, is the solution to revert back to AAD ?

**Comment by TiagoBrenck** [comment]
Hi @AhmedAzzabi, could you get the error message that you are receiving?

**Comment by jmprieur** [comment]
Closing as there was no answer?
