### ISSUE TITLE
OAuth 2.0 On-Behalf-Of Flow for Microsoft Personal Accounts

### ISSUE THREAD

**Issue by nkwolf** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> Please clarify what do you mean by "doesn't work" in:

"Current limitations:
The on-behalf-of flow does not currently work for Microsoft Personal accounts." 
The  [MSDN documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#consent-for-azure-ad--microsoft-account-applications) implies that OBO flow works for Microsoft Personal accounts. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nkwolf** [comment]
This is the only sample for implementing OAuth 2.0 OBO on AAD v2.0 and it excludes personal MSA accounts in a very _evasive_ manner.

> 

common | users can sign in with any Work and School account, or Microsoft Personal account. **Don't use it for the moment**. See [Current Limitations](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph#Current-limitations)
-- | --

And when we look at the _Current Limitations_, there's just a single sentence:

> **Current Limitations:**
> The on-behalf-of flow does not currently work for Microsoft Personal accounts.

Now "_does not currently work"_ is not exactly what I would call a "_limitation_". 

On the other hand, [MSDN](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow) documentation talks about these _limitations_ very differently:

> The v2.0 endpoint doesn't support all Azure AD scenarios and features. To determine whether you should use the v2.0 endpoint, read about v2.0 limitations. Specifically, known client applications are not supported for apps with Microsoft account (MSA) and Azure AD audiences. **Thus, a common consent pattern for OBO will not work for clients that sign in both personal and work or school accounts.** To learn more about how to handle this step of the flow, see [Gaining consent for the middle-tier application](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#gaining-consent-for-the-middle-tier-application).

By "_common-consent pattern for OBO will not work_" I don't necessarily understand the whole _"on-behalf-of-flow does not currently work for Microsoft Personal accounts_".

And when we follow the [Gaining consent for the middle-tier application](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#gaining-consent-for-the-middle-tier-application) it suggests to _use a single application_ (which, because of the language, is still not 100% clear whether it refers to getting rid of the whole middle-tier or just sharing the same AAD app registration from the front-end and middle-tier, but I'm guessing it's the latter.); and authenticate between the front-end and the web API, with cookies, an id_token, or an access token requested for the application itself. Then, request consent from this single application to the back-end resource.

So I followed this suggestion, created an app registration in the preview portal, defined the scopes, and used the same client id from both SPA & middle-tier however I couldn't get this to work. I do get sign-in and consent but the access token's audience is the downstream API not my middle-tier and I'm ending up with a 401 when I start making any calls to my middle-tier. 

My current solution, which I'm trying to migrate to Azure AD v2.0 consists of  a ReactJS SPA front-end (using msal.js) and a Service Fabric application middle-tier with a front-end stateless ASP.NET Core Web API making calls on-behalf-of the logged on user to build ML models & search index besides other things - giving as many details as I can to avoid recommendations such as why don't you just abandon the middle-tier).  

I'm not a security expert and just relying on our MSDN documentation & samples to implement this stuff, and being just ignored or referred to this very same page over & over is not really helping.

**Comment by jmprieur** [comment]
Thanks for your feedback @nkwolf 
This is a new feature and things are landing progressively
I have a work item to update the sample and provide concrete solutions. How blocking is it for you?

**Comment by nkwolf** [comment]
It is extremely blocking. 
Do you have an ETA for the work item? 
Any pointers/information to help us unblocked will be much appreciated.

**Comment by jmprieur** [comment]
@nkwolf I've updated the descriptions.
- OBO works for MSA.
- but the consent needs to happen on the Web API
  - and therefore the recommendation is to use the same client ID for the Web API and the client (and pass it and use it directly)

**Comment by nkwolf** [comment]
@jmprieur thanks a lot, I've got it working except for the consent.(I'm sharing the same client id between the native app and Web API). 

What should be right scope when acquiring token interactively from the client?

When I follow this instruction and set it to /.default

> Even if you declared the permission in the application registration to be (middletier)/access_as_user, in the code, you will need to acquire a token for (middletier)/.default in order to let the user consent to the downstream API (Graph) as well as the TodoListService. 

(api://e29f65bf-f00a-4e6b-90ea-551791483d4d/.default) it throws an **MsalException**:

`AADSTS90009: Application 'e29f65bf-f00a-4e6b-90ea-551791483d4d'(api://e29f65bf-f00a-4e6b-90ea-551791483d4d) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.`


And, just to confirm that it really doesn't work with the other setting as well -- when I leave it as /access_as_user, the consent page doesn't contain the graph scope (user.read) :

![image](https://user-images.githubusercontent.com/992432/56013221-88bd2580-5ca4-11e9-8736-689b686393d8.png)

And the downstream call can't be made since the Web API cannot acquire an OBO token with the user.read scope.

```
var result = application.AcquireTokenOnBehalfOf(requestedScopes.Except(scopesRequestedByMsalNet), userAssertion)
                                        .ExecuteAsync()
                                        .GetAwaiter().GetResult();
```

AADSTS65001: The user or administrator has not consented to use the application with ID 'e29f65bf-f00a-4e6b-90ea-551791483d4d' named 'TodoListServiceClientShared-v2'. Send an interactive authorization request for this user and resource.
Trace ID: 37892d93-3279-488b-9a1d-201bace40a00
Correlation ID: f2eb591a-a115-4a64-90a7-00c04aa9ae26
Timestamp: 2019-04-12 05:18:55Z

Please advice.

**Comment by jmprieur** [comment]
This is now working.
