### ISSUE TITLE
publish token issuer validators?

### ISSUE THREAD

**Issue by jepetty** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#46]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

This issue is more of a release question, so apologies if this isn't the right forum. 

Are you planning on publishing the AADIssuerValidator as a NuGet package, or including that as some kind of default option? We're in the process of migrating our app from tenant-restricted permissions to open to any account (work school personal). This example works like a charm, but it would be nice to not need to add the custom issue validation, but have it work a little more "out of the box" similar to the V1 token validation example.

Thanks for the help! :)

**Comment by jmprieur** [comment]
Yes, we are planning to release the library (Microsoft.Identity.Web) as a NuGet package.

**Comment by jmprieur** [comment]
Fixed in Microsoft.Identity.Web: https://github.com/AzureAD/microsoft-identity-web
