### ISSUE TITLE
The passed-in cache option should be used

### ISSUE THREAD

**Issue by bryanchen-d** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#62]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
At https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/ddeb6c3478f993271feb0f48a6d426c6ca5ce7e7/Microsoft.Identity.Web/Client/TokenCacheProviders/InMemory/MSALPerUserMemoryTokenCacheProvider.cs#L59-L67
`
if (option != null)
            {
                this.CacheOptions = new MSALMemoryTokenCacheOptions();
            }
`

It should actually be changed to 
`
if (option == null)
            {
                this.CacheOptions = new MSALMemoryTokenCacheOptions();
            }
`

**Comment by jmprieur** [comment]
Thanks @bryanchen-d for reporting this embarrassing bug.
cc; @kalyankrishna1 @TiagoBrenck 

I just fixed it.
