### ISSUE TITLE
Cache tokens per tenant

### ISSUE THREAD

**Issue by bryanchen-d** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#65]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
The existing token provider like MSALPerUserMemoryTokenCacheProvider persisting tokens by user id, however in the case of enumerating user's subscriptions (and also other resources) across tenants, it blocks the parallelizing of that. To solve that, it would be better to have the token persisted per user and per tenant. 

for example, add a member field `tenantId` to the cache provider, then for every place we need to read or load, append the tenantId to the key in cache, e.g.: change

```
this.memoryCache.Set(user.GetMsalAccountId(), ...)
```

to 
```
var cacheKey = user?.GetMsalAccountId()+"@"+tenantId;
this.memoryCache.Set(cacheKey, ...)
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@bryanchen-d : the MsalAccountId is made of <tenantId>.<UserObjectIdInAzureAd> already
I'm confused about what you are observing?
can you please elaborate on "it blocks the parallelizing of that"? is it something you are observing? or a theorical question?

**Comment by bryanchen-d** [comment]
> @bryanchen-d : the MsalAccountId is made of . already
> I'm confused about what you are observing?
> can you please elaborate on "it blocks the parallelizing of that"? is it something you are observing? or a theorical question?

Hi Jean, it is a theorical question for now based on my read of the code, as the key in cache is the same, every thread will overwrite the token for the same user. I haven't got a time yet but will give it a try later when I get to do the optimization work.

**Comment by jmprieur** [comment]
You don't override the token necessarily (which BTW accumulates claims). You override the cache, which will have several tokens in the case of a user present in several tenants. You are safe here, @bryanchen-d

**Comment by jmprieur** [comment]
Proposing to close. Feel free to reopen if you observe something different.
