### ISSUE TITLE
AadIssuerValidator does not actually validate the issuer

### ISSUE THREAD

**Issue by bryanchen-d** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#68]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Tested out that a fake access token with customized issuer can still pass the issuer validation. 
After debugging, the ValidateAadIssuer function at 
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/blob/7023f883b281229fdc9b920ddb4eb58fd760566a/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs#L128

it does not validate the passed-in issuer and simply return it. 

### Mention any other details that might be useful
My proposed fix would be to add a check against the issuer, changing 
```
if (IsValidIssuer(validationParameters.ValidIssuer, tenantId))
```
to
```
if (IsValidIssuer(validationParameters.ValidIssuer, tenantId) && validIssuer.Equals(issuer, StringComparison.InvariantCultureIgnoreCase))
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@bgavrilMS FYI as agreed.

**Comment by bgavrilMS** [comment]
PR here https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/117 (sorry it's on another repo, but same codebase). Once all changes are approved, I will merge the fix to both repos.

**Comment by bgavrilMS** [comment]
Fixed
