### ISSUE TITLE
CLEAR example with WebApi and SPA Application (pure js)

### ISSUE THREAD

**Issue by m4ss1m0g** [Azure-Samples/active-directory-dotnet-native-aspnetcore-v2#77]
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
It's possible to have a **CLEAR** example with 
- WebAPI with a controller protected `[Authorize]` by **JwtBearerToken**
- SPA Application (pure js) requesting token and passing to WebAPI ?

**Comment by TiagoBrenck** [comment]
@m4ss1m0g would this sample be what you are looking for? https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof

**Comment by m4ss1m0g** [comment]
An example where the backend api validate the token. 
Now the first example on description use code not found on repository and also use an external library  (made by Micosoft) without NuGet package.

For example on startup.cs code there are 

`AddProtectWebApiWithMicrosoftIdentityPlatformV2`

While on README there are code about

`.AddAzureAdBearer(options => Configuration.Bind("AzureAd", options));`

That must be inserted after

```
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
{
    // This is an Azure AD v2.0 Web API
    options.Authority += "/v2.0";

    // The valid audiences are both the Client ID (options.Audience) and api://{ClientID}
    options.TokenValidationParameters.ValidAudiences = new string[] { options.Audience, $"api://{options.Audience}" };

    // Instead of using the default validation (validating against a single tenant, as we do in line of business apps),
    // we inject our own multitenant validation logic (which even accepts both V1 and V2 tokens)
    options.TokenValidationParameters.IssuerValidator = AadIssuerValidator.ValidateAadIssuer;
});
```

No clues about `AddAzureAdBearer`, no clues about `AddProtectWebApiWithMicrosoftIdentityPlatformV2`



It wold be nice to have an example about:

0. Configuring Azure App, for authentication only
1. Simple javascript client aquiring token with MSAL.js calling ASP.NET Core API (Implicit Flow)
2. Simple ASP.NET Core API protected by Azure AD **ONLY validating token** so I can call Controller protected by  `[Authorize]` attribute
3. Exaplain difference between the use of _Token_ and _IdToken_ and 
and explain the use of one or the other.

**Comment by TiagoBrenck** [comment]
The external library, Microsoft.Identity.Web, is indeed not available yet but it is just a wrapper for some basic configurations. The README shows you code snippet of what is behind the `AddProtectWebApiWithMicrosoftIdentityPlatformV2` for example. We do that because we want to explain the developers what is happening behind the scenes, avoiding the "magically works" feeling. So, if you don't want to add Microsoft.Identity.Web to your project, you can copy the code on `StartupHelpers` directly to your `Startup.cs` and make the necessary customizations to it. 

For your question about IdToken, I believe you meant IdToken vs AccessToken. I will give you a brief explanation but you can find more details here: [IdToken](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) vs [AccessToken](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens).

- IdToken: Used for **Authentication**. It proves the identity of the user (you can see it as your passport).
- Access Token: Used for **Authorization**. It proves that you have access/permission to the resource (you can see it as a visa to a country).

**Comment by m4ss1m0g** [comment]
@TiagoBrenck Many Thanks ! My principal problem on authenticating to my .NET Api is the token.
I spend some hours to understand that I cannot use an *access_token* obtained with _microsoft.graph_ permission _user.read_ because it cannot be validated and is out of the **aud** of my app. I think that the docs must be updated this way. I must request a token with custom scope (`api://<appid/my_scope`) or use the id_token.

**Comment by jmprieur** [comment]
@m4ss1m0g : sorry that you wasted a lot of hours on this. 
Which documention did you look? we probably don't have our doc discoverable enought, and we'd want to make sure everybody understand that Web APIs only validate tokens for them, not for other APIs.

For the moment we mentionned this in:
- https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration#bearer-token (the blue comment)
- https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens (Important note)
- https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#modify-the-startupcs-file-so-that-the-web-api-becomes-v20-multi-tenant-app

Do you think that the way we phrase it is too ambigious? or that we should also surface it at other places?

**Comment by m4ss1m0g** [comment]
I would also add a better explanation between **idtoken** and **access_token** to [SPA Application](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa). For me, but I think for other people, a SPA application is a js app that accesses a secure Web API and not MSGraph. Anyway your help was greatly appreciated !

**Comment by devna13** [comment]
I've been looking for the same example that spa application (in my case angular with [MSAL-ANGULAR](https://www.npmjs.com/package/@azure/msal-angular) ) after successful login passes the access & idtoken token back to the web api that is protected with [Authorize] attribute and web api can read those tokens and extract username from the claims ( to do some audit logging etc..) and make calls on behalf of user.

**Comment by TiagoBrenck** [comment]
@devna13 we have [this Web API sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) that shows the on behalf of concept. We used a desktop application for the UI part, but you can have the same flow on your Angular application.

The SPA will get a token for the web API, then send the **access token** as a `bearer token` to the web api. Which then, will authenticate the user (this is covered in the sample link above) and make another call on behalf of the user.

**Comment by devna13** [comment]
Thanks @TiagoBrenck, and sorry for delay..

I get the user on the client side:
![65996553-7601fd00-e44c-11e9-99f6-642d6cabddf7](https://user-images.githubusercontent.com/4080343/66768300-21f11280-ee67-11e9-8865-e7239ecccbf0.png)

The [Authorize] call is failing, how can I get the logged in username/info on the webapi side ?
![65996073-8ebde300-e44b-11e9-9cd2-6a6651a06feb](https://user-images.githubusercontent.com/4080343/66768361-40570e00-ee67-11e9-82c3-e7cf86c49da9.png)


Also I've been following this post to setup the webapi app and client app on azure.
https://mobilefirstcloudfirst.net/2019/08/adding-azure-active-directory-authentication-connect-angular-app-asp-net-core-web-api-using-msal/

**Comment by TiagoBrenck** [comment]
@devna13 could you decorate this endpoint with the `Authorize` attribute?

**Comment by TiagoBrenck** [comment]
@devna13 I read the post that you followed to setup your app, and it seems to be missing some steps (for example, /.default scope, knowClientApplication on manifest, valid audience).
[This sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) shows you these steps and explains it on the README.md file. Could you try to configure your API using the sample steps?

**Comment by devna13** [comment]
ok I'll try the sample, Thanks @TiagoBrenck
